### PR TITLE
Add Scrabble Points

### PR DESCRIPTION
**Pull request by sefabey**
Added a point and frequency distribution for letters in the English language in accordance with the Scrabble game.

### CODE REVIEW

**Comment by romainfrancois** [comment]
Thanks. Can you please: 
- move the code to the data-raw/ directory
- have it finish by a call to usethis::use_data
- document the dataset with roxygen (see the words.R file for examples) 
- run devtools::document

**Comment by sefabey** [comment]
Is it looking better? Tried to incorporate previous comments but first time doing this.

**Comment by romainfrancois** [comment]
Thanks. I’ll have a look tonight. i assumed this was a new thing and decided to help you rather than directly do it.

**Comment by sefabey** [comment]
Thanks, much obliged.

**Comment by romainfrancois** [comment]
Better, still a few things. 
- remove the .DS_Store files
- use lower case letters in the dataset
- call the data set something shorter, like e.g. `scrabble` (or `data_scrabble`).

**Comment by sefabey** [comment]
Should be fine now?

**Review by romainfrancois — APPROVED** [review]

**Comment by romainfrancois** [comment]
Thanks

**Pull request merged**
